### ISSUE TITLE
Add github link in npm.com's sidepanel

### ISSUE THREAD

**Issue by falconmick** [wesbos/waait#4]
I see that none of your NPM packages have links to their github repos, it's no big deal but being able to check the code out without having to google around is just a nice gain.

see repository in the example bellow: 
https://www.npmjs.com/package/react
![image](https://user-images.githubusercontent.com/713449/38845175-13df786c-4229-11e8-836b-e6fa9c235e35.png)

**Comment by wesbos** [comment]
thanks - want to submit a PR?

**Comment by falconmick** [comment]
When I can get time to publish a package to debug why it's not showing I would... I thought your package.json would simply be missing repository, however you have:

```
  "repository": "wesbos/waait",
```

which works for react: https://github.com/facebook/react/blob/master/packages/react/package.json

perhapse you need to insert it manually? Otherwise you could try being more specific with your repository config via: https://docs.npmjs.com/files/package.json#repository

if you cannot find time to test these things out I'll try to find time, but I've got crazy schedule over next 2 weeks.

**Comment by falconmick** [comment]
perhapse your build server is omitting/using a different package.json?

**Comment by falconmick** [comment]
Success

![eaf5de9a-d0ff-4b0f-9d87-0c051844d850](https://user-images.githubusercontent.com/713449/39063177-93849f5e-44fc-11e8-8a9a-f63c9770961d.jpeg)
